
Neos:
  Neos:
    fusion:
      autoInclude:
        CodeQ.NeosMonocleRenderer: true
    userInterface:
      translation:
        autoInclude:
          CodeQ.NeosMonocleRenderer:
            - 'Fusion/*'
            - 'NodeTypes/*'

