
Neos:
  Neos:
    fusion:
      autoInclude:
        CodeQ.MonocleRenderer: true
    userInterface:
      translation:
        autoInclude:
          CodeQ.MonocleRenderer:
            - 'Fusion/*'
            - 'NodeTypes/*'

